In [1]:
import tensorflow as tf
import numpy as np

In [4]:
tensor_1 = tf.constant([[1,2], [2,3]])

In [7]:
print(tensor_1.shape)

(2, 2)


In [8]:
tensor_1_np = tensor_1.numpy()

In [9]:
print(np.square(tensor_1))

[[1 4]
 [4 9]]


In [10]:
print(np.dot(tensor_1, tensor_1))

[[ 5  8]
 [ 8 13]]


In [12]:
var_t = tf.Variable(tensor_1)
var_t[0,0].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[100,   2],
       [  2,   3]], dtype=int32)>

In [15]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(6, activation='linear', input_shape=[8]),
    tf.keras.layers.Dense(6, activation='relu'),
    tf.keras.layers.Dense(4, activation='softmax')
])

In [16]:
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [17]:
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 6)                 54        
_________________________________________________________________
dense_7 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_8 (Dense)              (None, 4)                 28        
Total params: 124
Trainable params: 124
Non-trainable params: 0
_________________________________________________________________
None


In [18]:
%load_ext tensorboard